name: kravata_sdk_plugin
description: "Este plugin permite una integracion directa con los servicios de widget kravata."
version: 1.0.0
homepage:

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.widget.kravata_sdk_plugin
        pluginClass: KravataSdkPlugin
      ios:
        pluginClass: KravataSdkPlugin